name: Release
on:
  push:
jobs:
  release:
    permissions: write-all
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: git tag ${{github.run_number}}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --example parkour --release --target x86_64-unknown-linux-gnu

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build#${{github.run_number}}"
          automatic_release_tag: "${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: target/x86_64-unknown-linux-gnu/release/examples
          prerelease: false